uid: abdul-baha
title: Writings and Talks of ‘Abdu’l‑Bahá
title_short: ‘Abdu’l‑Bahá
description: As Bahá’u’lláh’s successor and chosen interpreter of His Writings, ‘Abdu’l-Bahá expounded upon the teachings of His Father’s Faith, amplified its doctrines, and outlined the central features of its administrative institutions.
position: 30
