uid: the-bab
title: Writings of the Báb
title_short: The Báb
description: The Writings of the Báb—Prophet-Herald of the Bahá’í Faith—are revered by Bahá’ís as scripture. Almost all of the Báb’s works were composed during a period of seven years, from 1843 until His execution in July 1850 at the age of 30.
position: 20
